version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin <account-id>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t sample-codepipeline-app .
      - docker tag sample-codepipeline-app:latest <account-id>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/sample-codepipeline-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push <account-id>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/sample-codepipeline-app:latest

artifacts:
  files:
    - appspec.yml
    - taskdef.json
