version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    REPOSITORY_URI: 515800584100.dkr.ecr.us-east-1.amazonaws.com/simple-docker-service-12928efd52ff

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t simple-docker-service:latest .
      - docker tag simple-docker-service:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - echo Writing imagedefinitions.json file...
      - printf '[{"name":"simple-container","imageUri":"%s"}]' "$REPOSITORY_URI:latest" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
